version: '2'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
        image: postgres
        container_name: postgres-stubb
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=demo
            - POSTGRES_USER=anuroop
            - POSTGRES_PASSWORD=password
        restart: always
  # postgresql:
  #   image: 'bitnami/postgresql:latest'
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRESQL_USERNAME=anuroop
  #     - POSTGRESQL_PASSWORD=password
  #     - POSTGRESQL_DATABASE=demo
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
